create or replace PROCEDURE SHOWNAM 
IS COUNTER NUMBER; 
NAME NAMEARR; 
J NUMBER; 
CURSOR SHOWN IS 
SELECT NAME FROM FEST 
WHERE EXIST =1; 
BEGIN J :=1; 
FOR I IN SHOWN LOOP 
NAM(J) :=I.NAME; 
J :=J+1; 
END LOOP; 
COUNTER :=J-1; 
FOR J IN 1 .. COUNTER LOOP 
DBMS_OUTPUT.PUT_LINE(NAM(J)); 
END LOOP; 
END;