create or replace function SHOWNAME(ENAM IN VARCHAR2,COUNTER OUT NUMBER) 
return NAMEARR IS 
--COUNTER NUMBER; 
NAM NAMEARR; 
J NUMBER; 
TNAME VARCHAR2(20); 
JNAME VARCHAR2(20); 
CURSOR SHOWN IS 
SELECT NAME FROM FEST WHERE EXIST =1; 
BEGIN 
NAM :=NAMEARR(); 
J :=1; 
SELECT LOWER(ENAM) INTO JNAME FROM DUAL; 
FOR I IN SHOWN LOOP NAM.EXTEND; 
SELECT LOWER(I.NAME) INTO TNAME FROM DUAL; 
IF INSTR(TNAME,JNAME) !=0 THEN NAM(J) :=I.NAME; 
J :=J+1; 
END IF; 
END LOOP; 
COUNTER :=J-1; 
return nam; 
END;