create or replace PROCEDURE SHOWEVENT (NAM IN VARCHAR2,TNAME OUT VARCHAR2,TYP OUT VARCHAR2,VENU OUT VARCHAR2,DAT OUT DATE,
DET OUT VARCHAR2,LIN OUT VARCHAR2,DUR OUT NUMBER) 
IS BEGIN 
SELECT NAME,TYPE ,VENUE ,FDATE,DETAILS,LINK,DURATION INTO TNAME,TYP,VENU,DAT,DET,LIN,DUR FROM FEST 
WHERE NAME=NAM; END;


String d1  = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
