create or replace function SHOWREQEVENT(FSPONID IN NUMBER,COUNTER OUT NUMBER) 
return NAMEARR 
IS 
 NAM NAMEARR; 
 J NUMBER; 
 CURSOR SHOWN IS 
 SELECT NAME FROM FEST E,FESTSPONREQ F WHERE E.EXIST =1 AND F.SPONID=FSPONID AND F.FID=E.ID;
 BEGIN 
 NAM :=NAMEARR(); 
 J :=1; 
 FOR I IN SHOWN LOOP NAM.EXTEND; 
 NAM(J) :=I.NAME; J :=J+1; 
 END LOOP; 
 COUNTER :=J-1;
 return nam; 
 END;