CREATE TABLESPACE organizer
DATAFILE 'D:\Tablespaces\organizer. dbf ' SIZE 50M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE TABLESPACE sponsor
DATAFILE 'D:\Tablespaces\sponsor. dbf ' SIZE 50M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE TABLESPACE fest
DATAFILE 'D:\Tablespaces\fest. dbf ' SIZE 50M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE TABLESPACE sys
DATAFILE 'D:\Tablespaces\sys. dbf ' SIZE 50M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;