/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventsearcher2;

import java.sql.Array;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Shofol
 */
public class meetsponsor extends javax.swing.JFrame {

    /**
     * Creates new form example
     */
    Connection conn = null;
    organizerconnection a = null;

    public meetsponsor() {
        initComponents();

        try {
            conn = a.orgconnection();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(orgsignup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    String orgname = null;
    String orgpass = null;
    int orgid;
    int fid = -5;

    public void setorg(String name, String pass) throws SQLException {
        orgname = name;
        orgpass = pass;
        showEvent();
    }

    public void showEvent() throws SQLException {

        CallableStatement csmt = null;
        String proc = "{?= call admin.getorgid(?,?)}";
        csmt = conn.prepareCall(proc);
        csmt.registerOutParameter(1, Types.INTEGER);
        csmt.setString(2, orgname);
        csmt.setString(3, orgpass);
        csmt.execute();

        orgid = csmt.getInt(1);

        String pr = null;
        pr = "{?= call admin.showeventname(?,?)}";
        try {
            csmt = conn.prepareCall(pr);
            csmt.registerOutParameter(1, Types.ARRAY, "ADMIN.NAMEARR");
            csmt.setInt(2, orgid);

            csmt.registerOutParameter(3, Types.INTEGER);
            csmt.execute();

            Array arr = csmt.getArray(1);
            String[] data = null;
            if (arr != null) {
                data = (String[]) arr.getArray();
                int counter = csmt.getInt(3);
                for (int i = 0; i < counter; i++) {
                    Object Name = data[i];
                    Event.getModel().setValueAt(Name, i, 0);
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(searchdevent.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Event = new javax.swing.JTable();
        jFest = new javax.swing.JLabel();
        jTextg = new javax.swing.JTextField();
        jTextp = new javax.swing.JTextField();
        jTexts = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPlatinum = new javax.swing.JCheckBox();
        jGold = new javax.swing.JCheckBox();
        jSilver = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jButton1.setText("Home");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("<-");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSave.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jSave.setText("Save ");
        jSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jSave.setContentAreaFilled(false);
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });

        Event.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Event.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ));
        Event.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EventMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Event);

        jFest.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jFest.setForeground(new java.awt.Color(255, 255, 255));
        jFest.setToolTipText("");

        jTextg.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        jTextp.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        jTexts.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        jButton4.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jButton4.setText("Send Request");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPlatinum.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jPlatinum.setText("Platinum");

        jGold.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jGold.setText("Gold");

        jSilver.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jSilver.setText("Silver");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSave, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSilver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPlatinum, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jGold, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextp, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTexts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jFest))
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jFest)
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPlatinum))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jGold))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSilver)
                            .addComponent(jTexts, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jSave))
                .addGap(54, 54, 54))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventsearcher2/images/meetsponsor.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        orgoption a = new orgoption();
        a.setorg(orgname, orgpass);
        a.setVisible(true);
        this.dispose();
        try {
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(meetsponsor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        startpage a = new startpage();
        a.setVisible(true);
        this.dispose();
        try {
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(meetsponsor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            CallableStatement cs = null;

            String pr = "{?= call admin.GETFESTID(?)}";
            cs = conn.prepareCall(pr);
            cs.registerOutParameter(1, Types.INTEGER);
            cs.setString(2, jFest.getText());
            cs.execute();
            fid = cs.getInt(1);

            reqspon g = new reqspon();
            g.setVisible(true);
            this.dispose();
            g.setorg(orgname, orgpass, fid);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void EventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EventMouseClicked

        int sr = Event.getSelectedRow();

        String select = Event.getModel().getValueAt(sr, 0).toString();

        CallableStatement csmt = null;

        String proc = "{?= call admin.shown(?)}";

        try {
            csmt = conn.prepareCall(proc);
            csmt.registerOutParameter(1, Types.VARCHAR);
            csmt.setString(2, select);
            csmt.execute();
            String fname = csmt.getString(1);
            jFest.setText(fname);
        } catch (SQLException ex) {
            Logger.getLogger(searchdevent.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_EventMouseClicked

    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed

        CallableStatement csmt = null;
        CallableStatement cs = null;

        try {

            if (!jFest.getText().equals("")) {
                String pr = "{?= call admin.GETFESTID(?)}";
                cs = conn.prepareCall(pr);
                cs.registerOutParameter(1, Types.INTEGER);
                cs.setString(2, jFest.getText());
                cs.execute();
                fid = cs.getInt(1);

            } else {
                JOptionPane.showMessageDialog(rootPane, "Please, select a event!!");
            }

            String proc = "begin admin.SAVEFS(?,?,?);end;";

            boolean flag = false;
            csmt = conn.prepareCall(proc);
            boolean fl = false;

            if (jPlatinum.isSelected()) {

                CallableStatement cstmt = null;

                    if (!jTextp.getText().equals("")) {
                        csmt.setInt(1, fid);
                        csmt.setString(2, "Platinum");
                        csmt.setInt(3, Integer.parseInt(jTextp.getText()));
                        csmt.execute();

                        flag = true;
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Please insert platinum amount");
                    }
                    fl = true;
                } 
            if (jGold.isSelected()) {

                    if (!jTextg.getText().equals("")) {
                        csmt.setInt(1, fid);
                        csmt.setString(2, "Gold");
                        csmt.setInt(3, Integer.parseInt(jTextg.getText()));
                        csmt.execute();
                        flag = true;
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Please insert gold amount");
                    }
                    fl = true;

                 
            }
            if (jSilver.isSelected()) {

                    if (!jTexts.getText().equals("")) {
                        csmt.setInt(1, fid);
                        csmt.setString(2, "Silver");
                        csmt.setInt(3, Integer.parseInt(jTexts.getText()));
                        csmt.execute();
                        flag = true;
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Please insert silver amount");
                    }
                    fl = true;
            }
            if (flag) {
                JOptionPane.showMessageDialog(rootPane, "Data Saved Successfully!!");
            } else {
                if (!fl) {
                    JOptionPane.showMessageDialog(rootPane, "Please, select a module!!");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(meetsponsor.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(meetsponsor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(meetsponsor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(meetsponsor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(meetsponsor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new meetsponsor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Event;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jFest;
    private javax.swing.JCheckBox jGold;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jPlatinum;
    private javax.swing.JButton jSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jSilver;
    private javax.swing.JTextField jTextg;
    private javax.swing.JTextField jTextp;
    private javax.swing.JTextField jTexts;
    // End of variables declaration//GEN-END:variables
}
